services:
  app:
    build:
      context: .
    container_name: backend-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PORT: 8000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: app_db
      DB_USER: app_user
      DB_PASSWORD: app_password
    ports:
      - "8000:8000"
    restart: unless-stopped

  mysql:
    image: mysql:8.4
    container_name: backend-mysql
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_PASSWORD: root_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    ports:
      - "7500:3306"
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5-apache
    container_name: backend-phpmyadmin
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  mysql_data:
